/**
 * SpreadsheetPdfRenderer — Sheets-specific PDF rendering port (ADR-006).
 *
 * This is a Sheets-specific runtime port — NOT a generic Printing capability.
 * The renderer generates HTML (the print layout of the spreadsheet view);
 * the renderer port renders that HTML to PDF bytes.
 *
 * ARCHITECTURE (ADR-006):
 *   runtime-contracts
 *       SpreadsheetPdfRenderer (interface, data-only)
 *           ↓
 *   platform-electron
 *       ElectronSpreadsheetPdfRenderer (hidden BrowserWindow + printToPDF)
 *
 * The interface is DATA-ONLY. It must NOT expose:
 *   - BrowserWindow, WebContents
 *   - node:fs, node:path
 *   - File dialogs, save paths
 *   - wcId, renderer identity
 *
 * The interface accepts already-resolved HTML and print options, returns
 * PDF bytes (as Uint8Array). File-dialog ownership stays in the shell
 * coordinator.
 *
 * PAGE SIZE: the frozen IPC schema (WorkbookExportPdfRequest) uses either
 * an enum ('A3', 'A4', 'A5', 'Legal', 'Letter', 'Tabloid') or a custom
 * size in inches. The renderer port accepts the same union — the
 * Electron implementation maps it to Electron's printToPDF options.
 */

// ── PDF page size ────────────────────────────────────────────────────

/**
 * Page size for PDF rendering.
 *
 * Either a named standard size or a custom width/height in inches.
 * Mirrors the frozen WorkbookExportPdfRequest.pageSize union so the
 * coordinator can pass it through without translation.
 */
export type SpreadsheetPdfPageSize =
  | 'A3'
  | 'A4'
  | 'A5'
  | 'Legal'
  | 'Letter'
  | 'Tabloid'
  | { width: number; height: number }

// ── PDF margins ──────────────────────────────────────────────────────

/**
 * Page margins in inches.
 */
export interface SpreadsheetPdfMargins {
  readonly top: number
  readonly bottom: number
  readonly left: number
  readonly right: number
}

// ── PDF render options ──────────────────────────────────────────────

/**
 * Options for rendering HTML to PDF.
 *
 * All fields mirror the frozen WorkbookExportPdfRequest schema so the
 * coordinator can pass them through without translation.
 */
export interface SpreadsheetPdfOptions {
  /** Landscape orientation. */
  readonly landscape: boolean
  /** Page size (named or custom inches). */
  readonly pageSize: SpreadsheetPdfPageSize
  /** Margins in inches. */
  readonly margins: SpreadsheetPdfMargins
  /** Scale factor (0.1 to 2.0). */
  readonly scale: number
}

// ── PDF render result ───────────────────────────────────────────────

/**
 * Result of rendering HTML to PDF.
 *
 * SUCCESS: carries the PDF bytes (as Uint8Array).
 * ERROR: carries a typed error message.
 *
 * The renderer port returns PDF bytes ONLY. The shell coordinator owns
 * writing those bytes to the user-authorized output path.
 */
export type SpreadsheetPdfRenderResult =
  | { readonly ok: true; readonly data: Uint8Array }
  | { readonly ok: false; readonly reason: 'render-failed'; readonly message: string }

// ── Renderer interface ─────────────────────────────────────────────

/**
 * Sheets-specific PDF rendering port (ADR-006).
 *
 * The implementation owns:
 *   - The hidden BrowserWindow (or equivalent rendering context)
 *   - HTML loading
 *   - printToPDF invocation
 *   - Window destruction / resource cleanup
 *   - Timeout / error handling
 *
 * The implementation must NOT leak BrowserWindow / WebContents outside
 * the adapter. The interface exposes only data (HTML in, PDF bytes out).
 *
 * The interface is runtime-independent — a WASM renderer (direct PDF
 * generation from the spreadsheet model) or a Cloud renderer (server-side
 * HTML→PDF) would implement the same interface.
 */
export interface SpreadsheetPdfRenderer {
  /**
   * Render the given HTML to PDF bytes.
   *
   * @param html — the print-layout HTML (generated by the renderer)
   * @param options — page size, margins, scale, orientation
   * @returns the PDF bytes on success, or a typed error on failure
   *
   * THROWS: never — errors are returned as `{ ok: false, ... }` so the
   * coordinator can map them to the frozen IPC error shape without
   * catching typed exceptions.
   *
   * RESOURCE CLEANUP: the implementation MUST destroy any hidden
   * BrowserWindow and clean up any temp files in all cases (success,
   * error, timeout). Use try/finally internally.
   */
  renderToPdf(
    html: string,
    options: SpreadsheetPdfOptions,
  ): Promise<SpreadsheetPdfRenderResult>
}
