/**
 * Contractor GenOffice — shared browser styles.
 *
 * Reuses the GenOffice design language from packages/ui/src/tokens.css
 * (surface/border/text/danger tokens) per ADR-0001 D2 (substrate reuse) and
 * Phase 2C.1 §22 ("feel like one product"). Commercial-specific UI lives here;
 * no Office-specific primitives imported (the Commercial workspace is its own
 * domain UI, per §22).
 *
 * No design polish — this is a vertical-slice proof. (§27, §23)
 */

import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  app: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background: 'var(--surface, #ffffff)',
    color: 'var(--text, #242424)',
    fontFamily: 'var(--gs-font-sans, system-ui, -apple-system, sans-serif)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 24px',
    borderBottom: '1px solid var(--border, #e3e6ea)',
    background: 'var(--chrome-bg, #ffffff)',
  },
  headerTitle: { fontSize: 16, fontWeight: 600, margin: 0 },
  headerRight: { display: 'flex', alignItems: 'center', gap: 12 },
  main: { flex: 1, padding: '24px', maxWidth: 1100, width: '100%', margin: '0 auto' },
  loading: { padding: 48, textAlign: 'center', color: 'var(--text-secondary, #606366)' },
  screen: { display: 'flex', flexDirection: 'column', gap: 16 },
  title: { fontSize: 22, fontWeight: 600, margin: 0 },
  subtitle: { fontSize: 14, color: 'var(--text-secondary, #606366)', margin: 0 },
  card: {
    border: '1px solid var(--border, #e3e6ea)',
    borderRadius: 8,
    padding: 16,
    background: 'var(--surface, #ffffff)',
  },
  row: { display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' },
  column: { display: 'flex', flexDirection: 'column', gap: 8 },
  label: { fontSize: 13, fontWeight: 500, color: 'var(--text-secondary, #606366)' },
  value: { fontSize: 14 },
  input: {
    padding: '8px 12px',
    border: '1px solid var(--border, #e3e6ea)',
    borderRadius: 6,
    fontSize: 14,
    background: 'var(--surface, #ffffff)',
    color: 'var(--text, #242424)',
    minWidth: 0,
  },
  button: {
    padding: '8px 16px',
    border: '1px solid var(--border, #e3e6ea)',
    borderRadius: 6,
    background: 'var(--surface, #ffffff)',
    color: 'var(--text, #242424)',
    fontSize: 14,
    cursor: 'pointer',
  },
  buttonPrimary: {
    padding: '8px 16px',
    border: '1px solid var(--accent, #2563eb)',
    borderRadius: 6,
    background: 'var(--accent, #2563eb)',
    color: '#ffffff',
    fontSize: 14,
    cursor: 'pointer',
    fontWeight: 500,
  },
  buttonDanger: {
    padding: '8px 16px',
    border: '1px solid var(--danger, #d13438)',
    borderRadius: 6,
    background: 'var(--danger-bg, #fdf3f3)',
    color: 'var(--danger, #d13438)',
    fontSize: 14,
    cursor: 'pointer',
  },
  buttonDisabled: {
    padding: '8px 16px',
    border: '1px solid var(--border, #e3e6ea)',
    borderRadius: 6,
    background: 'var(--surface-subtle, #f6f7f9)',
    color: 'var(--text-tertiary, #909499)',
    fontSize: 14,
    cursor: 'not-allowed',
  },
  error: {
    padding: '12px 16px',
    border: '1px solid var(--danger-border, #f0c8c9)',
    borderRadius: 6,
    background: 'var(--danger-bg, #fdf3f3)',
    color: 'var(--danger, #d13438)',
    fontSize: 14,
  },
  success: {
    padding: '12px 16px',
    border: '1px solid #c6f6d5',
    borderRadius: 6,
    background: '#f0fff4',
    color: '#22543d',
    fontSize: 14,
  },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 14 },
  th: {
    textAlign: 'left',
    padding: '8px 12px',
    borderBottom: '2px solid var(--border, #e3e6ea)',
    fontWeight: 600,
    fontSize: 13,
    color: 'var(--text-secondary, #606366)',
  },
  td: { padding: '8px 12px', borderBottom: '1px solid var(--border-subtle, #efefef)' },
  badge: {
    display: 'inline-block',
    padding: '2px 8px',
    borderRadius: 12,
    fontSize: 12,
    fontWeight: 500,
    background: 'var(--surface-subtle, #f6f7f9)',
    color: 'var(--text-secondary, #606366)',
  },
  badgeFinalized: {
    display: 'inline-block',
    padding: '2px 8px',
    borderRadius: 12,
    fontSize: 12,
    fontWeight: 500,
    background: '#f0fff4',
    color: '#22543d',
  },
  badgeSubmitted: {
    display: 'inline-block',
    padding: '2px 8px',
    borderRadius: 12,
    fontSize: 12,
    fontWeight: 500,
    background: '#ebf8ff',
    color: '#2a4365',
  },
  tabRow: { display: 'flex', gap: 4, borderBottom: '1px solid var(--border, #e3e6ea)' },
  tab: {
    padding: '8px 16px',
    border: 'none',
    background: 'transparent',
    color: 'var(--text-secondary, #606366)',
    fontSize: 14,
    cursor: 'pointer',
    borderBottom: '2px solid transparent',
  },
  tabActive: {
    padding: '8px 16px',
    border: 'none',
    background: 'transparent',
    color: 'var(--text, #242424)',
    fontSize: 14,
    cursor: 'pointer',
    borderBottom: '2px solid var(--accent, #2563eb)',
    fontWeight: 500,
  },
  muted: { color: 'var(--text-secondary, #606366)', fontSize: 13 },
  mono: { fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', fontSize: 12 },
  warning: {
    padding: '12px 16px',
    border: '1px solid #fbd38d',
    borderRadius: 6,
    background: '#fffaf0',
    color: '#7b341e',
    fontSize: 14,
  },
}
