/**
 * createSlidesApiBridge — maps window.slidesApi (SlidesApi) to
 * PresentationService + platform capabilities.
 *
 * The PresentationService is NOT_YET_WIRED. Service-specific methods
 * throw via `notYet()`. Cross-cutting methods (settings, AI, windowing)
 * delegate to runtime capabilities.
 *
 * Uses explicit conversions (toLegacyLanguage) — NO `as never` / `as any`.
 */
import type { SlidesApi } from '@genoffice/slides-shared'
import type { RuntimeContext } from '@genoffice/runtime-contracts'
import { toLegacyLanguage, wrapLanguageHandler } from '../conversions/docs-conversions.js'
import { notYet } from './not-yet.js'

export function createSlidesApiBridge(runtime: RuntimeContext): SlidesApi {
  return {
    getLanguage: () => runtime.settings.getLanguage().then(toLegacyLanguage),
    onLanguageChanged: (handler) => runtime.settings.onLanguageChanged(wrapLanguageHandler(handler)),
    getTheme: () => runtime.settings.getTheme(),
    onThemeChanged: (handler) => runtime.settings.onThemeChanged(handler),
    onChromePressed: (handler) => runtime.windowing.onChromePressed(handler),
    setShowFullScreen: (on) => runtime.windowing.setProgressBar(on ? 2 : -1).then(() => undefined),

    openPptx: notYet.bind(null, 'PresentationService'),
    openPptxPath: notYet.bind(null, 'PresentationService'),
    privateFontFaces: notYet.bind(null, 'PresentationService'),
    privateFontData: notYet.bind(null, 'PresentationService'),
    consumePendingOpen: notYet.bind(null, 'PresentationService'),
    newBlank: notYet.bind(null, 'PresentationService'),
    htmlToPptx: notYet.bind(null, 'PresentationService'),
    cloudGenStatus: notYet.bind(null, 'PresentationService'),
    cloudGeneratePage: notYet.bind(null, 'PresentationService'),
    editText: notYet.bind(null, 'PresentationService'),
    setElementFont: notYet.bind(null, 'PresentationService'),
    setElementParagraphFormat: notYet.bind(null, 'PresentationService'),
    findReplace: notYet.bind(null, 'PresentationService'),
    setSlideLayout: notYet.bind(null, 'PresentationService'),
    setSlideSize: notYet.bind(null, 'PresentationService'),
    getSlideSize: notYet.bind(null, 'PresentationService'),
    editTransform: notYet.bind(null, 'PresentationService'),
    editConnectorEndpoints: notYet.bind(null, 'PresentationService'),
    batchEditTransform: notYet.bind(null, 'PresentationService'),
    getRenderSlides: notYet.bind(null, 'PresentationService'),
    editPictureSrcRect: notYet.bind(null, 'PresentationService'),
    editPictureOpacity: notYet.bind(null, 'PresentationService'),
    editImageFill: notYet.bind(null, 'PresentationService'),
    setTextAnchor: notYet.bind(null, 'PresentationService'),
    clipboardExternal: notYet.bind(null, 'PresentationService'),
    groupElements: notYet.bind(null, 'PresentationService'),
    ungroupElement: notYet.bind(null, 'PresentationService'),
    addElement: notYet.bind(null, 'PresentationService'),
    deleteElement: notYet.bind(null, 'PresentationService'),
    addSlide: notYet.bind(null, 'PresentationService'),
    addBlankSlide: notYet.bind(null, 'PresentationService'),
    copySlide: notYet.bind(null, 'PresentationService'),
    pasteSlide: notYet.bind(null, 'PresentationService'),
    repasteSlide: notYet.bind(null, 'PresentationService'),
    hasSlideClipboard: notYet.bind(null, 'PresentationService'),
    deleteSlide: notYet.bind(null, 'PresentationService'),
    reorderElement: notYet.bind(null, 'PresentationService'),
    editTableCell: notYet.bind(null, 'PresentationService'),
    tableStructure: notYet.bind(null, 'PresentationService'),
    tableMerge: notYet.bind(null, 'PresentationService'),
    setTableColWidth: notYet.bind(null, 'PresentationService'),
    setTableRowHeight: notYet.bind(null, 'PresentationService'),
    setTableCellAnchor: notYet.bind(null, 'PresentationService'),
    editFill: notYet.bind(null, 'PresentationService'),
    editStroke: notYet.bind(null, 'PresentationService'),
    flipElements: notYet.bind(null, 'PresentationService'),
    editBackground: notYet.bind(null, 'PresentationService'),
    insertImage: notYet.bind(null, 'PresentationService'),
    copyElements: notYet.bind(null, 'PresentationService'),
    pasteElements: notYet.bind(null, 'PresentationService'),
    duplicateElements: notYet.bind(null, 'PresentationService'),
    addTable: notYet.bind(null, 'PresentationService'),
    addInk: notYet.bind(null, 'PresentationService'),
    addChart: notYet.bind(null, 'PresentationService'),
    addSmartArt: notYet.bind(null, 'PresentationService'),
    addImageBytes: notYet.bind(null, 'PresentationService'),
    replacePictureBytes: notYet.bind(null, 'PresentationService'),
    insertMedia: notYet.bind(null, 'PresentationService'),
    addMediaBytes: notYet.bind(null, 'PresentationService'),
    getMediaData: notYet.bind(null, 'PresentationService'),
    insertModel3d: notYet.bind(null, 'PresentationService'),
    setLink: notYet.bind(null, 'PresentationService'),
    getLink: notYet.bind(null, 'PresentationService'),
    getSlideLinks: notYet.bind(null, 'PresentationService'),
    getRunLinks: notYet.bind(null, 'PresentationService'),
    applyHeaderFooter: notYet.bind(null, 'PresentationService'),
    getHeaderFooter: notYet.bind(null, 'PresentationService'),
    applyTheme: notYet.bind(null, 'PresentationService'),
    setTransition: notYet.bind(null, 'PresentationService'),
    getTransition: notYet.bind(null, 'PresentationService'),
    setAdvanceTimes: notYet.bind(null, 'PresentationService'),
    getAnimations: notYet.bind(null, 'PresentationService'),
    getShapeKeys: notYet.bind(null, 'PresentationService'),
    setAnimations: notYet.bind(null, 'PresentationService'),
    setSlideHidden: notYet.bind(null, 'PresentationService'),
    getSections: notYet.bind(null, 'PresentationService'),
    setSections: notYet.bind(null, 'PresentationService'),
    addSection: notYet.bind(null, 'PresentationService'),
    renameSection: notYet.bind(null, 'PresentationService'),
    removeSection: notYet.bind(null, 'PresentationService'),
    moveSection: notYet.bind(null, 'PresentationService'),
    moveSlide: notYet.bind(null, 'PresentationService'),
    getNotes: notYet.bind(null, 'PresentationService'),
    setNotes: notYet.bind(null, 'PresentationService'),
    getComments: notYet.bind(null, 'PresentationService'),
    addComment: notYet.bind(null, 'PresentationService'),
    deleteComment: notYet.bind(null, 'PresentationService'),
    nativeClipboard: notYet.bind(null, 'PresentationService'),
    beginHistoryBatch: notYet.bind(null, 'PresentationService'),
    endHistoryBatch: notYet.bind(null, 'PresentationService'),
    aiSnapshotRestore: notYet.bind(null, 'PresentationService'),
    undo: notYet.bind(null, 'PresentationService'),
    redo: notYet.bind(null, 'PresentationService'),
    editTableStyle: notYet.bind(null, 'PresentationService'),
    editChart: notYet.bind(null, 'PresentationService'),
    getChartColorSchemes: notYet.bind(null, 'PresentationService'),
    getChartData: notYet.bind(null, 'PresentationService'),
    pickExportDir: notYet.bind(null, 'PresentationService'),
    exportImages: notYet.bind(null, 'PresentationService'),
    pickExportPdfPath: notYet.bind(null, 'PresentationService'),
    exportPdf: notYet.bind(null, 'PresentationService'),
    printSlides: notYet.bind(null, 'PresentationService'),
    save: notYet.bind(null, 'PresentationService'),
    saveAs: notYet.bind(null, 'PresentationService'),
    onCloseSaveRequest: notYet.bind(null, 'PresentationService'),
    onHistoryChanged: notYet.bind(null, 'PresentationService'),
    reportCloseSaveResult: notYet.bind(null, 'PresentationService'),
    setAutoSavePref: notYet.bind(null, 'PresentationService'),
    isDirty: notYet.bind(null, 'PresentationService'),
    getRecentFiles: notYet.bind(null, 'PresentationService'),
    onMenuCommand: notYet.bind(null, 'PresentationService'),
    onOpened: notYet.bind(null, 'PresentationService'),
    onRenamed: notYet.bind(null, 'PresentationService'),
    getAiSettings: () => runtime.ai.getSettings(),
    setAiSettings: (settings) => runtime.ai.setSettings(settings),
    aiStream: (request) => runtime.ai.stream(request),
    aiStreamCancel: (requestId) => runtime.ai.streamCancel(requestId),
    aiGskStatus: () => runtime.identity.accountStatus(),
    aiGskLogin: () => runtime.identity.login().then(() => undefined),
    webSearch: (query, maxResults) => runtime.ai.webSearch(query, maxResults),
    imageSearch: (query, maxResults) => runtime.ai.imageSearch(query, maxResults),
    insertImageUrl: notYet.bind(null, 'PresentationService'),
    replacePictureUrl: notYet.bind(null, 'PresentationService'),
    generateImage: notYet.bind(null, 'PresentationService'),
    analyzeMedia: notYet.bind(null, 'PresentationService'),
    gskStatus: () => runtime.identity.accountStatus().then((s) => ({ available: s.loggedIn, email: s.email })),
    onAiStream: (handler) => runtime.ai.onStream(handler),
    saveStyleSidecar: notYet.bind(null, 'PresentationService'),
    saveStyleTemplate: notYet.bind(null, 'PresentationService'),
    listStyleTemplates: notYet.bind(null, 'PresentationService'),
    loadStyleTemplate: notYet.bind(null, 'PresentationService'),
    addSlideWithLayout: notYet.bind(null, 'PresentationService'),
    getLayouts: notYet.bind(null, 'PresentationService'),
    masterEnter: notYet.bind(null, 'PresentationService'),
    masterOpen: notYet.bind(null, 'PresentationService'),
    masterClose: notYet.bind(null, 'PresentationService'),
    masterEditText: notYet.bind(null, 'PresentationService'),
    masterEditTransform: notYet.bind(null, 'PresentationService'),
    masterEditFill: notYet.bind(null, 'PresentationService'),
    masterEditStroke: notYet.bind(null, 'PresentationService'),
    masterDeleteElement: notYet.bind(null, 'PresentationService'),
    presenterStart: notYet.bind(null, 'PresentationService'),
    presenterSync: notYet.bind(null, 'PresentationService'),
    presenterInk: notYet.bind(null, 'PresentationService'),
    presenterSwap: notYet.bind(null, 'PresentationService'),
    presenterEnd: notYet.bind(null, 'PresentationService'),
    audienceReady: notYet.bind(null, 'PresentationService'),
    audienceNav: notYet.bind(null, 'PresentationService'),
    onShowSync: notYet.bind(null, 'PresentationService'),
    onShowInk: notYet.bind(null, 'PresentationService'),
    onAudienceNav: notYet.bind(null, 'PresentationService'),
  }
}
